### ISSUE TITLE
Fix alignment/size inconsistency of navigation bar icons

### ISSUE THREAD

**Issue by tsitra** [tsitra/horsebooks#10]

**Comment by KeystrokeCascade** [comment]
I've almost finished tackling this
![image](https://user-images.githubusercontent.com/35793455/50752607-f0796400-12a2-11e9-8c8f-2acd627edab1.png)

**Comment by KeystrokeCascade** [comment]
Done.
![image](https://user-images.githubusercontent.com/35793455/50753234-39cab300-12a5-11e9-80b9-5ca82c8b47f9.png)

**Comment by KeystrokeCascade** [comment]
Do you want me to do the same with the home button or leave as is?

**Comment by tsitra** [comment]
Bugs should remain in the top bar.
Text should exist in desktop view but be hidden in the mobile view.
And Home should be given the same treatment, yes.

**Comment by tsitra** [comment]
Fixed in 41066f1beeabf9684936800844cd4147a6e3a5f1
