### ISSUE TITLE
[Desktop/Tablet] Fix card display

### ISSUE THREAD

**Issue by tsitra** [tsitra/horsebooks#11]
Some entries have an excessive number of links, which can cause the entire card to not display, preventing the item from even displaying all proper links.

In mobile, this is not an issue as the card is dynamic height, but as cards are static height in desktop/tablet mode, some information is not displayed

**Comment by KeystrokeCascade** [comment]
Would having a singular "link" button that would then expand when clicked work?

**Comment by tsitra** [comment]
Potentially. Using the current template, I've found that doing something like that actually messes up the row layout, which is worse than what we have.

I think the best solution is both a summary view (the list/table) and a detail view, which is elaborated in #12 but as that's a higher cost ask, making a better summary view in the short term might be quicker, hence the two issues, not 1.

**Comment by tsitra** [comment]
Angular uses a slightly different syntax:

/#path/to/route?param=value

**Comment by tsitra** [comment]
It needs some investigation regardless.

**Comment by KeystrokeCascade** [comment]
I think having one page that queries the data from json would be the easiest and most adaptive. I'm not the developer here though.

**Comment by tsitra** [comment]
The JSON data is already loaded through a service, called by the various views that would need it. Presently, that's only the index view, but a detail view could just as easily query the JSON data for rendering out the appropriate information.

**Comment by tsitra** [comment]
Will get fixed in #12
