### ISSUE TITLE
Fimfic2epub

### ISSUE THREAD

**Issue by KeystrokeCascade** [tsitra/horsebooks#32]
Add a link to fimfiction.djazz.se for djazz's fimfic2epub tool.

**Comment by tsitra** [comment]
Have to confirm that's the right link, because there's also http://fimfic2epub.nl/

**Comment by tsitra** [comment]
Also, still not sure it's appropriate. I say this, but I'm also the one who originally was toying with the idea and told you to go ahead and put it in as an issue.

**Comment by tsitra** [comment]
I don't think this is ultimately appropriate for the service we're trying to provide. That's an eBook maker. We're dealing with physical goods.
