### ISSUE TITLE
[BUG] Expired checkbox text cut off and no Discord link

### ISSUE THREAD

**Issue by KeystrokeCascade** [tsitra/horsebooks#56]
**Describe the bug**
Expired checkbox cut off and Discord link missing in Firefox Linux

**To Reproduce**
1. Load the page in relevant OS + Browser
2. It's there

**Expected behavior**
For the Discord link to be there and have no cut-off text

**Screenshots**
![image](https://user-images.githubusercontent.com/35793455/53848351-0d62b700-4008-11e9-9b52-a08d55993b2d.png)
![image](https://user-images.githubusercontent.com/35793455/53848371-1d7a9680-4008-11e9-835e-1dda865f84b1.png)

**Desktop:**
 - Antergos Linux (KDE)
 - Firefox v65.0.1

**Additional Notes**
Not sure if this happens in other browsers or OS', but reloading the page produced the exact same result, it might be due to system fonts or something.

**Comment by tsitra** [comment]
Checked in 
OSX 10.14.3
Firefox 65.0.1

Cannot reproduce.

**Comment by tsitra** [comment]
Of note, I do not have access to a Linux desktop environment I can test with. If I don't know how it's broken, I can't fix it.

If someone else wants to take it on to fix, that's fine.

**Comment by KeystrokeCascade** [comment]
Further testing leads me to assume this is an issue with my client than the website itself.
